blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='home'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import MessageListView, MessageCreateView, MessageUpdateView, \
    MessageDetailView, MessageDeleteView, MailingCreateView, MailingUpdateView, MailingDeleteView, MailingListView, \
    MailingDetailView, ClientListView, ClientCreateView, ClientUpdateView, MailingUpdateModeratorView, \
    IndexView

app_name = MailingConfig.name


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('mailing_list', MailingListView.as_view(), name='mailing_list'),
    path('mailing_add/', MailingCreateView.as_view(), name='mailing_add'),
    path('mailing_view/<int:pk>', MailingDetailView.as_view(), name='mailing_view'),
    path('mailing_edit/<int:pk>/', MailingUpdateView.as_view(), name='mailing_edit'),
    path('mailing_mod_edit/<int:pk>/', MailingUpdateModeratorView.as_view(), name='mailing_mod_edit'),
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_add/', MessageCreateView.as_view(), name='message_add'),
    path('message_edit/<int:pk>/', MessageUpdateView.as_view(), name='message_edit'),
    path('message_view/<int:pk>/', MessageDetailView.as_view(), name='message_view'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('client_add/', ClientCreateView.as_view(), name='client_add'),
    path('client_edit/<int:pk>', ClientUpdateView.as_view(), name='client_edit'),
]

users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path
from django.views.generic import TemplateView

from users.apps import UsersConfig
from users.views import RegisterView, verification, UserUpdateView, get_users_list

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(template_name='users/register.html'), name='register'),
    path('verify_message/', TemplateView.as_view(template_name='users/verify_message.html'), name='verify_message'),
    path('email/verify/<str:verify_code>', verification, name='verify'),
    path('success_verify/', TemplateView.as_view(template_name='users/success_verify.html'), name='success_verify'),
    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'), name='invalid_verify'),
    path('users_list/', get_users_list, name='list_view'),
    path('edit/<int:pk>', UserUpdateView.as_view(), name='edit')
]

blog/models.py
from django.db import models

from mailing.models import NULLABLE


class Blog(models.Model):
    title = models.CharField(max_length=250, verbose_name='Заголовок', default='Заголовок отсутствует')
    content = models.TextField(verbose_name='Текст', default='Текст отсутствует')
    preview = models.ImageField(upload_to='blog/preview/', verbose_name='Изображение', **NULLABLE)
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')
    public_date = models.DateField(auto_now=True, verbose_name='Дата публикации')

    def __str__(self):
        return self.title

mailing/models.py
from django.db import models
from django.utils import timezone

from users.models import User

NULLABLE = {'blank': True, 'null': True}

STATUS_CHOICES = [
    ('Создана', 'Создана'),
    ('Запущена', 'Запущена'),
    ('Завершена', 'Завершена'),
]
INTERVAL_CHOICES = [
    ('Разово', 'Разово'),
    ('Ежедневно', 'Ежедневно'),
    ('Раз в неделю', 'Раз в неделю'),
    ('Раз в месяц', 'Раз в месяц'),
]


class Client(models.Model):
    name = models.CharField(max_length=200, verbose_name='ФИО')
    email = models.EmailField(verbose_name='Почта')
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Владелец клиента')

    def __str__(self):
        return f'{self.name}({self.owner})'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    title = models.CharField(max_length=250, verbose_name='Тема письма')
    content = models.TextField(verbose_name='Содержание')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Автор')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Mailing(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование рассылки')
    mail_to = models.ManyToManyField(Client, verbose_name='Кому')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Сообщение', **NULLABLE)
    start_date = models.DateTimeField(default=timezone.now, verbose_name='Вреия начала рассылки')
    second_date = models.DateTimeField(default=timezone.now, verbose_name='Врея следующей рассылки')
    end_date = models.DateTimeField(default=timezone.now, verbose_name='Время окончания рассылки')
    interval = models.CharField(choices=INTERVAL_CHOICES, max_length=60, default='разовая',
                                verbose_name='Периодичность')
    status = models.CharField(choices=STATUS_CHOICES, max_length=60, help_text='Создана или Завершена',
                              verbose_name='Статус рассылки')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='CСоздатель рассылки', null=True)
    is_active = models.BooleanField(default=True, verbose_name='Активна')

    def __str__(self):
        return f'{self.name}(Кому: {self.mail_to}, Дата создания: {self.start_date}, Статус: {self.status})'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ('start_date',)

    permissions = [
        ('set_is_active', 'Может отключать рассылку')
    ]


class Logs(models.Model):
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка', null=True)
    last_mailing = models.DateTimeField(auto_now=True, verbose_name='Дата последней рассылки')
    status = models.CharField(**NULLABLE, max_length=60, verbose_name='Статус отправки')

    def __str__(self):
        return f'Отправлено: {self.last_mailing}/n Статус: {self.status}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

mailing/forms.py
from django.forms import ModelForm
from django.forms import DateTimeInput

from mailing.models import Mailing, Message, Client


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        user = self.request.user
        super().__init__(*args, **kwargs)
        self.fields['mail_to'].queryset = Client.objects.filter(owner=user)
        self.fields['message'].queryset = Message.objects.filter(owner=user)

    class Meta:
        model = Mailing
        exclude = ('next_date', 'owner', 'is_active',)

        widgets = {
            'start_date': DateTimeInput(attrs={'placeholder': 'ДД.ММ.ГГГГ ЧЧ:ММ:СС', 'type': 'datetime-local'}),
            'end_date': DateTimeInput(attrs={'placeholder': 'ДД.ММ.ГГГГ ЧЧ:ММ:СС', 'type': 'datetime-local'}),
        }


class MailingModeratorForm(StyleFormMixin, ModelForm):

    class Meta:
        model = Mailing
        fields = ('is_active',)


class MessageForm(StyleFormMixin, ModelForm):

    class Meta:
        model = Message
        exclude = ('owner',)


class ClientForm(StyleFormMixin, ModelForm):

    class Meta:
        model = Client
        exclude = ('owner',)

mailing/views.py
from django.shortcuts import render

import random
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from mailing.models import Client, Mailing, Message, Logs
from mailing.forms import ClientForm, MailingForm, MessageForm, MailingModeratorForm
from mailing.services import get_cache_for_mailings, get_cache_for_active_mailings
from blog.models import Blog


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    extra_context = {
        'title': 'Создание рассылки'
    }

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def form_valid(self, form, *args, **kwargs):
        if form.is_valid():
            new_mailing = form.save(commit=False)
            new_mailing.owner = self.request.user
            new_mailing.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('mailing:mailing_list')


class MailingUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return self.request.user == Mailing.objects.get(pk=self.kwargs['pk']).owner


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    extra_context = {
        'title': 'Список рассылок'
    }


class MailingDetailView(DetailView):
    model = Mailing

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['clients'] = list(self.object.mail_to.all())
        context_data['logs'] = list(Logs.objects.filter(mailing=self.object))
        return context_data


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')


class MailingUpdateModeratorView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingModeratorForm
    success_url = reverse_lazy('mailing:mailing_list')
    permission_required = 'mailing.set_is_active'


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_list')
    extra_context = {
        'title': 'Создание сообщения'
    }

    def form_valid(self, form):
        new_message = form.save()
        new_message.owner = self.request.user
        new_message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm

    def get_success_url(self):
        return reverse('mailing:message_view', args=[self.kwargs.get('pk')])


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    extra_context = {
        'title': 'Список сообщений'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = Message.objects.filter(owner=self.request.user)
        return queryset


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:message_list')


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    extra_context = {
        'title': 'Список клиентов'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = Client.objects.filter(owner=self.request.user)
        return queryset


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')
    extra_context = {
        'title': 'Добавить клиента'
    }

    def form_valid(self, form):
        new_client = form.save()
        new_client.owner = self.request.user
        new_client.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def test_func(self):
        return self.request.user == Client.objects.get(pk=self.kwargs['pk']).owner


class IndexView(ListView):
    model = Mailing
    template_name = 'mailing/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['mailing_count'] = get_cache_for_mailings()
        context_data['active_mailing_count'] = get_cache_for_active_mailings()
        blog_list = list(Blog.objects.all())
        random.shuffle(blog_list)
        context_data['blog_list'] = blog_list[:3]
        context_data['clients_count'] = len(Client.objects.all())
        return context_data

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Automail Service</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h1 class="my-0 mr-md-auto font-weight-normal">Automail Service</h1><br>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:index' %}">На главную</a>

        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:mailing_list' %}">Рассылки</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:message_list' %}">Сообщения</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:client_list' %}">Клиенты</a>
        {% endif %}

        {% if perms.mailings.set_is_active %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:list_view' %}">Пользователи</a>
        {% endif %}
        {% if user.is_authenticated %}
            <p>{{ user.email }}</p>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>

{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            AutomailsService
            <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
        </div>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends "mailing/base.html" %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Удалить клиента {{ object.name }}?</p>
                        <button type="submit" class="btn btn-success">Удалить</button>
                        <a href="{% url 'mailing:client_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="header mx-auto text-center">
    <h5 class="display-4">{{ title }}</h5>
</div>
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if object %}
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        {% else %}
                            <button type="submit" class="btn btn-primary">Создать</button>
                        {% endif %}
                        <a href="{% url 'mailing:client_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="header mx-auto text-center">
    <h5 class="display-4">{{ title }}</h5>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailing:client_add' %}">Добавить клиента</a>
</div>
<div class="col-12">
    <div class="row">
        {% for object in object_list %}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">{{ object.full_name|title }}</h3>
                    </div>
                    <div class="card-body">
                        <p>{{ object.email }}</p>
                        {% if object.comment %}
                            <p>{{ object.comment }}</p>
                        {% endif %}
                        <a href="{% url 'mailing:client_edit' object.pk %}"
                           class="btn btn-sm btn-outline-secondary">Редактировать</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

mailing/templates/mailing/index.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h3 class="display-4">Automail Service</h3>
    <p class="lead">Automail Service - сервис управления рассылками.</p>
</div>
<div class="container">
    <div class="col-12">
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            <div class="col-4">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Всего рассылок в сервисе</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ mailing_count }}</h1>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Всего активных рассылок</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ active_mailing_count }}</h1>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Число уникальных клиентов</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ clients_count }}</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        {% for blog in blog_list %}
            <div class="col-6">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">

                        <h3 class="mb-0">{{ blog.title }}</h3>
                        <div class="mb-1 text-muted">{{ blog.public_date }}</div>
                        <p class="card-text mb-auto">{{ blog.content }}</p>
                        <a href="#" class="stretched-link">Читать полностью</a>
                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img"
                             aria-label="Placeholder: Blog" preserveAspectRatio="xMidYMid slice" focusable="false">
                            <title>Placeholder</title>
                            <rect width="100%" height="100%" fill="#55595c"/>
                            <text x="50%" y="50%" fill="#eceeef" dy=".3em">Блог</text>
                        </svg>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Удалить рассылку "{{ object.name }}"?</p>
                            <button type="submit" class="btn btn-primary">Подтвердить</button>
                            <a href="{% url 'mailing:index' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Название:</td>
                            <td>{{ object.name }}</td>
                        </tr>
                        <tr>
                            <td>Тема сообщения:</td>
                            <td>{{ object.message.title }}</td>
                        </tr>
                        <tr>
                            <td>Кому:</td>
                            <td>{{ clients }}</td>
                        </tr>
                        <tr>
                            <td>Старт рассылки:</td>
                            <td>{{ object.start_date }}</td>
                        </tr>
                        <tr>
                            <td>Периодичность:</td>
                            <td>{{ object.interval }}</td>
                        </tr>
                        <tr>
                            <td>Завершение рассылки:</td>
                            <td>{{ object.end_date }}</td>
                        </tr>
                        <tr>
                            <td>Текущий статус:</td>
                            <td>{{ object.status }}</td>
                        </tr>
                    </table>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        {% if perms.mailing.set_is_active %}
                            <a href="{% url 'mailing:mailing_mod_edit' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-primary">Редактировать</a>
                        {% else %}
                            <a href="{% url 'mailing:mailing_edit' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-primary">Редактировать</a>
                            <a href="{% url 'mailing:mailing_delete' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-danger">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% for log in logs %}
                        <p>{{ log }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="header mx-auto text-center">
        <h5 class="display-4">{{ title }}</h5>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="fieldWrapper">
                            {{ field.label_tag }} {{ field }}
                            {% if field.help_text %}
                                <p class="help" id="{{ field.auto_id }}_helptext">
                                    {{ field.help_text|safe }}
                                </p>
                            {% endif %}
                        </div>
                    {% endfor %}

                    {% if object %}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    {% else %}
                        <button type="submit" class="btn btn-primary">Создать</button>
                    {% endif %}
                    <a href="{% url 'mailing:index' %}" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="header mx-auto text-center">
    <h5 class="display-4">{{ title }}</h5>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailing:mailing_add' %}">Создать рассылку</a>
</div>
<div class="col-12">
    <div class="row">
        {% for object in object_list %}
            {% if user == object.owner or perms.mailing.view_mailing %}
            <div class="col-6 mb-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">Рассылка {{ object.name }}</h3>
                    </div>
                    <div class="card-body">
                        <p>с {{ object.start_date }} по {{ object.end_date }}</p>
                        <p>с периодичностью {{ object.interval }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{% url 'mailing:mailing_view' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-primary">Подробнее</a>
                        </div>
                        <div class="card-footer">
                            {% if object.is_active %}
                            <p>Активна</p>
                            {% else %}
                            <p>Отменена</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Удалить сообщение "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-primary">Подтвердить</button>
                            <a href="{% url 'mailing:message_list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                    </div>
                    <div class="card-body">
                        <p>{{ object.content }}</p>
                        {% if user == object.owner %}
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'mailing:message_edit' object.pk %}" type="button"
                                       class="btn btn-sm btn-outline-secondary">Редактировать</a>
                                    <a href="{% url 'mailing:message_delete' object.pk %}" type="button"
                                       class="btn btn-sm btn-outline-danger">Удалить</a>
                                    <a href="{% url 'mailing:message_list' %}" class="btn btn-warning">Отмена</a>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="header mx-auto text-center">
        <h5 class="display-4">{{ title }}</h5>
    </div>
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'mailing:message_add' %}">Создать сообщение для рассылки</a>
    </div>
    <div class="col-12">
        <div class="row">
            {% for object in object_list %}
                <div class="col-6 mb-3">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="my-0 font-weight-normal">{{ object.title }}</h3>
                        </div>
                        <div class="card-body">
                            <p>{{ object.content }}</p>
                            <a href="{% url 'mailing:message_view' object.pk %}"
                               class="btn btn-sm btn-outline-secondary">Просмотр</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}